# DVC Parameters for Weather Prediction Model

# Data extraction
extract:
  city: "London"
  country: "GB"
  include_forecast: true

# Data quality thresholds
quality:
  max_null_ratio: 0.01
  min_rows: 100

# Feature engineering
features:
  lag_hours: [1, 2, 3, 6, 12, 24]
  rolling_windows: [3, 6, 12, 24]
  forecast_horizon: 6

# Model training
train:
  model_type: "xgboost"
  n_estimators: 100
  max_depth: 6
  learning_rate: 0.1
  subsample: 0.8
  colsample_bytree: 0.8
  random_state: 42
  test_size: 0.2
  
# Cross-validation
cv:
  n_splits: 5
  shuffle: true

